openapi: "3.0.0"

info:
  title: T-Shirt Store API
  description: SPB - a course to create API for Ecom Store
  version: 1.1.0
  contact:
    email: pro.paddusonu@gmail.com
    url: "http://SPB.dev"

# Servers
# servers:
#   - url: "https://localhost:4000/api/v1"
#     description: For Local Host - secure


# # Servers
servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: For Local Host 
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http
        

#Authentication        
components:
  securitySchemes:
    cookieAuth: 
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummyroute:
    get:
      tags:
        - String
      summary: returns a greet message from LCO
      responses:
        '200': #status code
          description: All good success
          content:
            application/json:
              schema: 
                type: string
                example: "mystring"
        '400': #status code
          description: Bad Request